### ISSUE TITLE
Docker Version wont update

### ISSUE THREAD

**Issue by GustelDE** [LinkStackOrg/linkstack-docker#126]
Hi,

I am runnign Docker version 4.8.0 and saw today the update notificationin in the admin-dashboard.
Opened, clicked the automatic-updater, it said success 4.8.0 -> 4.8.3

But in the admin-dashboard, it's still 4.8.0, also under debug information: 4.8.0.
What to do?

**Comment by lastsamurai26** [comment]
For some reason the Updater doesn't work at all but you can replace the updater file with this one, after that the Updater should work - This file should fix this problem  - this issue is not releated to our docker images 

https://github.com/LinkStackOrg/LinkStack/blob/main/resources/views/update.blade.php

**Comment by GustelDE** [comment]
Hi,

thank you this worked!
For all Docker-user, I did the following steps:

1. clear old file (owner/groups persist this way):
sudo truncate -s 0  /var/lib/docker/volumes/[CONTAINER-NAME]_data/_data/resources/views/update.blade.php

2. copy content form link above and edit:
sudo nano /var/lib/docker/volumes/[CONTAINER-NAME]_data/_data/resources/views/update.blade.php
CTRL + O (save)
CTRL + X (exit nano)

Updater worked after change without restarting container.
"/var/lib/docker/volumes/..." is the path under Ubuntu, I can not speak for every Linux.
