### ISSUE TITLE
Setup Linkstack to different port (no 80 or 443)

### ISSUE THREAD

**Issue by L041S** [LinkStackOrg/linkstack-docker#95]
Hello,
I'm trying to setup the docker image like my previous ones : I usually run the container on a specific port, for example 8090 and then I use an nginx reverse proxy to move requests from 443 to let's say 8090 and voila.

But I can't figure how to make the docker image of Linkstack use my own port, it's always trying to use 80 or 443. Is it possible to make the container on 8090 ?
Here is an exemple in the screenshot, the first line is the linkstack container trying to use 80 and 443 and the others are some of my containers runing on their ports.

Even if I launch linkstack with --publish 8090:8090, it seems that it uses 80 or 443
![Capture d’écran du 2023-10-23 01-57-13](https://github.com/LinkStackOrg/linkstack-docker/assets/60223861/5581b4a0-3eda-488f-9c95-f1710ae68107)

**Comment by lastsamurai26** [comment]
You can only change the port outside of the container not inside because inside of the container is running a webserver and it isn’t possible to change it. 

But if you running a Reverse Proxy you can change the lines port to #ports and so on.
after that you don’t need to change the ports anymore because you are running a reverse Proxy with a network
